<?php

/**
 * @file
 * Various logic related to elm application.
 */

/**
 * Implements hook_preprocess_HOOK().
 *
 * @todo: Why is this needed, as we already have
 * \Drupal\server_elm\Plugin\Block\ElmAppBlock::build that tries to attach
 * library.
 */
function server_elm_preprocess_block(&$variables) {
  if ($variables['configuration']['provider'] != 'server_elm') {
    return;
  }

  $variables['#attached']['library'][] = 'server_elm/elm-application';
}
